'use client'

// ** Next Imports
import { Router } from 'next/router'

// ** Loader Import
import NProgress from 'nprogress'

// ** Config Imports
import themeConfig from 'src/configs/themeConfig'

// ** Component Imports
import ThemeComponent from 'src/@core/theme/ThemeComponent'

// ** Contexts
import { SettingsConsumer, SettingsProvider } from 'src/@core/context/settingsContext'

// ** React Perfect Scrollbar Style
import 'react-perfect-scrollbar/dist/css/styles.css'

// ** Global css styles
import '../../styles/globals.css'

import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

// ** Pace Loader
if (themeConfig.routingLoader) {
  Router.events.on('routeChangeStart', () => {
    NProgress.start()
  })
  Router.events.on('routeChangeError', () => {
    NProgress.done()
  })
  Router.events.on('routeChangeComplete', () => {
    NProgress.done()
  })
}

import React from 'react'

export default function RootLayout({ children }: { children: React.ReactElement }) {
  return (
    <html lang="en">
    <head>
      <title>Create Next App</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/public/favicon.ico"/>
    </head>
    <body>
    <SettingsProvider>
      <SettingsConsumer>
        {({ settings }) => {
          return <ThemeComponent settings={settings}>{children}</ThemeComponent>
        }}
      </SettingsConsumer>
    </SettingsProvider>
    </body>
    </html>
  )
}
